@startuml
participant ProgrammePolyglotte
participant Eval
participant BlocLangage
participant BlocCode
participant Source0
participant StringLiteral
participant RawCode
participant FileCode
participant File
participant NewBuilder
participant Identifier
participant Language

ProgrammePolyglotte -> Eval : 
Eval -> BlocLangage : 
Eval -> BlocCode : 
Eval -> Source0 : identifier*
BlocLangage -> Language : 
Language -> StringLiteral : identifier*
BlocCode -> RawCode :
BlocCode -> FileCode :
RawCode -> StringLiteral : identifier*
FileCode -> File : identifier*
File -> StringLiteral : identifier*
Source0 -> NewBuilder : identifier*
NewBuilder -> BlocLangage : 
NewBuilder -> BlocCode : 
@enduml
