@startuml
participant PolyglotFinder
participant RefAnalysis
participant SourceFinder
participant BuildFinder
participant LanguageFinder
participant CodeFinder

PolyglotFinder -> SourceFinder 
SourceFinder -> RefAnalysis
RefAnalysis -> BuildFinder
BuildFinder -> LanguageFinder
BuildFinder -> CodeFinder
CodeFinder -> BuildFinder
LanguageFinder -> BuildFinder
BuildFinder -> SourceFinder
SourceFinder -> RefAnalysis
RefAnalysis -> PolyglotFinder
@endmul